// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type User struct {
	ID                string    `json:"id"`
	Username          string    `json:"username"`
	FirstName         string    `json:"first_name"`
	LastName          string    `json:"last_name"`
	HashedPassword    string    `json:"hashed_password"`
	Email             string    `json:"email"`
	UserType          int32     `json:"user_type"`
	Active            int32     `json:"active"`
	CreatedAt         time.Time `json:"created_at"`
	LastAccessedAt    time.Time `json:"last_accessed_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
}
