// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type User struct {
	ID             string         `json:"id"`
	Username       sql.NullString `json:"username"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Email          sql.NullString `json:"email"`
	UserType       sql.NullInt32  `json:"user_type"`
	Active         sql.NullBool   `json:"active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
}
