// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    username,
    first_name,
    last_name,
    hashed_password,
    email,
    user_type,
    active,
    created_at,
    last_accessed_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, username, first_name, last_name, hashed_password, email, user_type, active, created_at, last_accessed_at
`

type CreateUserParams struct {
	ID             string         `json:"id"`
	Username       sql.NullString `json:"username"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	HashedPassword sql.NullString `json:"hashed_password"`
	Email          sql.NullString `json:"email"`
	UserType       sql.NullInt32  `json:"user_type"`
	Active         sql.NullBool   `json:"active"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	LastAccessedAt sql.NullTime   `json:"last_accessed_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
		arg.HashedPassword,
		arg.Email,
		arg.UserType,
		arg.Active,
		arg.CreatedAt,
		arg.LastAccessedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.HashedPassword,
		&i.Email,
		&i.UserType,
		&i.Active,
		&i.CreatedAt,
		&i.LastAccessedAt,
	)
	return i, err
}
